services:
  catalogue:
    uri: http://localhost:8081
    registration-id: keycloak
spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/manager
#    username: manager
#    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/app
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: xygTn1WA86L1WbhJ9QH10EJcfKYNjtJE
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt